FROM eclipse-temurin:17-jdk-alpine as build
LABEL authors="tsilva"

WORKDIR ./

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM eclipse-temurin:17-jre-alpine
LABEL authors="tsilva"

VOLUME /tmp
ARG DEPENDENCY=./target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","dev/silvasolutions/springboottemplate/SpringBootTemplateApplication"]